-- 0039: transactional program writes (sweep report step 4).
-- program/commit and program/save were long chains of single-row PostgREST
-- calls; a mid-sequence failure left a client with no active program (the
-- commit route deactivated the old program BEFORE inserting the new one)
-- or a half-written edit. Each function below runs as one transaction:
-- any failure rolls the whole write back. The TS routes keep all planning
-- logic (validation, name_key collation, diffing, id generation) and pass
-- a fully-resolved payload; these functions only execute it atomically.
--
-- swap_exercises replaces the archive-then-insert + "best-effort revert"
-- in suggestions/apply, and enforces ownership (exercise -> day ->
-- program -> client) inside the transaction. increment_prescribed_sets
-- makes add_set a single atomic statement instead of read-then-write.

-- ---------------------------------------------------------------------------
-- Sheet upload: deactivate old actives + insert program/days/exercises.
-- p_days: [{ label, exercises: [{ name, name_key, prescription_raw,
--            prescribed_sets, rep_min, rep_max, rir_target, is_cardio,
--            cardio_type }] }]
-- ---------------------------------------------------------------------------
create or replace function commit_program(
  p_client_id uuid,
  p_program_id uuid,
  p_source_filename text,
  p_days jsonb
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  d jsonb;
  e jsonb;
  v_day_id uuid;
  di int := 0;
  ei int;
begin
  perform 1 from public.clients where id = p_client_id;
  if not found then
    return jsonb_build_object('error', 'client_not_found');
  end if;

  update public.programs
  set active = false
  where client_id = p_client_id and active;

  insert into public.programs (id, client_id, source_filename, active)
  values (p_program_id, p_client_id, p_source_filename, true);

  for d in select * from jsonb_array_elements(p_days) loop
    di := di + 1;
    insert into public.days (program_id, day_index, label)
    values (p_program_id, di, d->>'label')
    returning id into v_day_id;

    ei := 0;
    for e in select * from jsonb_array_elements(d->'exercises') loop
      ei := ei + 1;
      insert into public.exercises
        (day_id, position, name, name_key, prescription_raw, prescribed_sets,
         rep_min, rep_max, rir_target, is_cardio, cardio_type)
      values
        (v_day_id, ei, e->>'name', e->>'name_key', e->>'prescription_raw',
         (e->>'prescribed_sets')::int, (e->>'rep_min')::int,
         (e->>'rep_max')::int, e->>'rir_target',
         coalesce((e->>'is_cardio')::boolean, false), e->>'cardio_type');
    end loop;
  end loop;

  return jsonb_build_object('ok', true, 'program_id', p_program_id);
end;
$$;

-- ---------------------------------------------------------------------------
-- In-place program edit. Ids (including for new rows) are generated by the
-- route so the response can reference them without a round trip back.
-- p_days: [{ id, is_new, day_index, label, exercises: [{ id, is_new,
--            position, name, name_key, prescription_raw, prescribed_sets,
--            rep_min, rep_max, rir_target, is_cardio, coach_note,
--            muscle_group }] }]
-- Renumbering strategy: archive removed exercises first (they keep their
-- original positions for history ordering), stash every remaining live
-- position out of the way, then write final positions 1..N — collision-free
-- for any permutation under the partial unique (day_id, position) index.
-- day_index renumbering relies on the deferrable unique from 0035.
-- ---------------------------------------------------------------------------
create or replace function save_program_edit(
  p_client_id uuid,
  p_program_id uuid,
  p_days jsonb,
  p_archive_ids uuid[]
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  d jsonb;
  e jsonb;
  v_day_id uuid;
begin
  perform 1 from public.programs
  where id = p_program_id and client_id = p_client_id and active;
  if not found then
    return jsonb_build_object('error', 'program_not_found');
  end if;

  set constraints public.days_program_id_day_index_key deferred;

  if coalesce(array_length(p_archive_ids, 1), 0) > 0 then
    update public.exercises ex
    set archived_at = now()
    from public.days dd
    where ex.id = any(p_archive_ids)
      and ex.day_id = dd.id
      and dd.program_id = p_program_id
      and ex.archived_at is null;
  end if;

  update public.exercises ex
  set position = ex.position + 100000
  from public.days dd
  where ex.day_id = dd.id
    and dd.program_id = p_program_id
    and ex.archived_at is null;

  for d in select * from jsonb_array_elements(p_days) loop
    v_day_id := (d->>'id')::uuid;
    if (d->>'is_new')::boolean then
      insert into public.days (id, program_id, day_index, label)
      values (v_day_id, p_program_id, (d->>'day_index')::int, d->>'label');
    else
      update public.days
      set day_index = (d->>'day_index')::int, label = d->>'label'
      where id = v_day_id and program_id = p_program_id;
      if not found then
        raise exception 'day % is not part of program %', v_day_id, p_program_id;
      end if;
    end if;

    for e in select * from jsonb_array_elements(d->'exercises') loop
      if (e->>'is_new')::boolean then
        insert into public.exercises
          (id, day_id, position, name, name_key, prescription_raw,
           prescribed_sets, rep_min, rep_max, rir_target, is_cardio,
           coach_note, muscle_group)
        values
          ((e->>'id')::uuid, v_day_id, (e->>'position')::int, e->>'name',
           e->>'name_key', e->>'prescription_raw', (e->>'prescribed_sets')::int,
           (e->>'rep_min')::int, (e->>'rep_max')::int, e->>'rir_target',
           coalesce((e->>'is_cardio')::boolean, false),
           e->>'coach_note', e->>'muscle_group');
      else
        update public.exercises
        set position = (e->>'position')::int,
            name = e->>'name',
            name_key = e->>'name_key',
            prescription_raw = e->>'prescription_raw',
            prescribed_sets = (e->>'prescribed_sets')::int,
            rep_min = (e->>'rep_min')::int,
            rep_max = (e->>'rep_max')::int,
            rir_target = e->>'rir_target',
            is_cardio = coalesce((e->>'is_cardio')::boolean, false),
            coach_note = e->>'coach_note',
            muscle_group = e->>'muscle_group',
            archived_at = null
        where id = (e->>'id')::uuid and day_id = v_day_id;
        if not found then
          raise exception 'exercise % is not part of day %', e->>'id', v_day_id;
        end if;
      end if;
    end loop;
  end loop;

  -- Every live exercise must have been renumbered or archived; a row left
  -- in the stash range means the payload missed it — fail (and roll back)
  -- rather than persist phantom positions.
  perform 1
  from public.exercises ex
  join public.days dd on dd.id = ex.day_id
  where dd.program_id = p_program_id
    and ex.archived_at is null
    and ex.position >= 100000;
  if found then
    raise exception 'payload did not account for all live exercises';
  end if;

  update public.programs
  set last_edited_at = now()
  where id = p_program_id;

  return jsonb_build_object('ok', true);
end;
$$;

-- ---------------------------------------------------------------------------
-- Suggestion apply: swap exercises for a replacement, atomically, with
-- ownership enforced. Archived ids in the input are skipped (idempotent
-- re-apply); ids belonging to another client reject the whole call.
-- ---------------------------------------------------------------------------
create or replace function swap_exercises(
  p_client_id uuid,
  p_exercise_ids uuid[],
  p_replacement_name text
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_foreign int;
  v_active_ids uuid[];
  v_replaced int;
begin
  select count(*) into v_foreign
  from unnest(p_exercise_ids) as t(id)
  where not exists (
    select 1
    from public.exercises ex
    join public.days dd on dd.id = ex.day_id
    join public.programs p on p.id = dd.program_id
    where ex.id = t.id and p.client_id = p_client_id
  );
  if v_foreign > 0 then
    return jsonb_build_object('error', 'ownership_mismatch');
  end if;

  select coalesce(array_agg(ex.id), '{}') into v_active_ids
  from public.exercises ex
  join public.days dd on dd.id = ex.day_id
  join public.programs p on p.id = dd.program_id
  where ex.id = any(p_exercise_ids)
    and ex.archived_at is null
    and p.client_id = p_client_id;

  if coalesce(array_length(v_active_ids, 1), 0) = 0 then
    return jsonb_build_object('error', 'no_active_matches');
  end if;

  update public.exercises
  set archived_at = now()
  where id = any(v_active_ids);

  insert into public.exercises
    (day_id, position, name, name_key, prescription_raw, prescribed_sets,
     rep_min, rep_max, rir_target, is_cardio, cardio_type)
  select
    ex.day_id, ex.position, p_replacement_name,
    'd' || dd.day_index || '::' ||
      lower(regexp_replace(btrim(p_replacement_name), '\s+', ' ', 'g')),
    ex.prescription_raw, ex.prescribed_sets, ex.rep_min, ex.rep_max,
    ex.rir_target, false, null
  from public.exercises ex
  join public.days dd on dd.id = ex.day_id
  where ex.id = any(v_active_ids);

  get diagnostics v_replaced = row_count;
  return jsonb_build_object('ok', true, 'replaced', v_replaced);
end;
$$;

-- ---------------------------------------------------------------------------
-- Suggestion apply: add a set — atomic increment (was read-then-write per
-- row) with ownership enforced. Returns the affected exercise names for
-- the push/audit copy.
-- ---------------------------------------------------------------------------
create or replace function increment_prescribed_sets(
  p_client_id uuid,
  p_exercise_ids uuid[]
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_foreign int;
  v_names text[];
begin
  select count(*) into v_foreign
  from unnest(p_exercise_ids) as t(id)
  where not exists (
    select 1
    from public.exercises ex
    join public.days dd on dd.id = ex.day_id
    join public.programs p on p.id = dd.program_id
    where ex.id = t.id and p.client_id = p_client_id
  );
  if v_foreign > 0 then
    return jsonb_build_object('error', 'ownership_mismatch');
  end if;

  with updated as (
    update public.exercises ex
    set prescribed_sets = coalesce(ex.prescribed_sets, 2) + 1
    from public.days dd
    join public.programs p on p.id = dd.program_id
    where ex.day_id = dd.id
      and ex.id = any(p_exercise_ids)
      and p.client_id = p_client_id
    returning ex.name
  )
  select coalesce(array_agg(name), '{}') into v_names from updated;

  if coalesce(array_length(v_names, 1), 0) = 0 then
    return jsonb_build_object('error', 'no_matches');
  end if;

  return jsonb_build_object('ok', true, 'updated', array_length(v_names, 1), 'names', to_jsonb(v_names));
end;
$$;
